project_id = "pldxyuesaachuhdfrfvh"

[functions.generate-document]
verify_jwt = false

[functions.generate-facture]
verify_jwt = false

[functions.generate-devis]
verify_jwt = false

[functions.analyze-logo]
verify_jwt = false

[functions.suggest-tasks]
verify_jwt = false
