project_id = "pldxyuesaachuhdfrfvh"

[functions.generate-document]
verify_jwt = false

[functions.generate-facture]
verify_jwt = false

[functions.generate-devis]
verify_jwt = false

[functions.analyze-logo]
verify_jwt = false

[functions.suggest-tasks]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.studio-ia-generate]
verify_jwt = false

[functions.dashboard-ai-summary]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false
