// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-clients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool({
  name: "list_clients",
  title: "Lister les clients",
  description: "Liste les clients de l'entreprise de l'utilisateur connect\xE9.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Nombre maximum de clients \xE0 retourner.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const { data, error } = await sb(ctx).from("clients").select("id, nom, email, telephone, created_at").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-properties.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_properties_default = defineTool2({
  name: "list_properties",
  title: "Lister les biens",
  description: "Liste les biens immobiliers de l'entreprise de l'utilisateur connect\xE9.",
  inputSchema: {
    statut: z2.enum(["disponible", "reserve"]).optional().describe("Filtrer par statut."),
    limit: z2.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ statut, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    let q = sb2(ctx).from("properties").select("*").order("created_at", { ascending: false }).limit(limit);
    if (statut) q = q.eq("statut", statut);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { properties: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-reservations.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_reservations_default = defineTool3({
  name: "list_reservations",
  title: "Lister les r\xE9servations",
  description: "Liste les r\xE9servations de l'entreprise de l'utilisateur connect\xE9.",
  inputSchema: {
    statut: z3.enum(["en_attente", "en_cours", "terminee", "annulee"]).optional(),
    limit: z3.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ statut, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    let q = sb3(ctx).from("reservations").select("*").order("date_arrivee", { ascending: false }).limit(limit);
    if (statut) q = q.eq("statut", statut);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { reservations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-factures.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_factures_default = defineTool4({
  name: "list_factures",
  title: "Lister les factures",
  description: "Liste les factures de l'entreprise de l'utilisateur connect\xE9.",
  inputSchema: {
    statut: z4.enum(["brouillon", "envoyee", "paye", "en_retard", "annulee"]).optional(),
    limit: z4.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ statut, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    let q = sb4(ctx).from("factures").select("*").order("date", { ascending: false }).limit(limit);
    if (statut) q = q.eq("statut", statut);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { factures: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-client.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_client_default = defineTool5({
  name: "create_client",
  title: "Cr\xE9er un client",
  description: "Cr\xE9e un nouveau client dans l'entreprise de l'utilisateur connect\xE9.",
  inputSchema: {
    nom: z5.string().trim().min(1).describe("Nom complet du client."),
    email: z5.string().email().optional().describe("Email du client."),
    telephone: z5.string().optional().describe("Num\xE9ro de t\xE9l\xE9phone."),
    adresse: z5.string().optional().describe("Adresse.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ nom, email, telephone, adresse }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const client = sb5(ctx);
    const { data: profile, error: pErr } = await client.from("profiles").select("entreprise_id").eq("id", ctx.getUserId()).maybeSingle();
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    if (!profile?.entreprise_id) {
      return { content: [{ type: "text", text: "Aucune entreprise associ\xE9e \xE0 cet utilisateur." }], isError: true };
    }
    const { data, error } = await client.from("clients").insert({ nom, email: email ?? null, telephone: telephone ?? null, adresse: adresse ?? null, entreprise_id: profile.entreprise_id }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Client cr\xE9\xE9: ${data.nom} (${data.id})` }],
      structuredContent: { client: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pldxyuesaachuhdfrfvh";
var mcp_default = defineMcp({
  name: "optimum-immo-mcp",
  title: "Optimum Immo MCP",
  version: "0.1.0",
  instructions: "Outils pour Optimum Immo. Chaque appel agit en tant que l'utilisateur connect\xE9 et respecte les permissions par entreprise (RLS).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_clients_default,
    list_properties_default,
    list_reservations_default,
    list_factures_default,
    create_client_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
